name: Build
on:
  workflow_dispatch:
  push:
    branches:
    - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Theos
      uses: Randomblock1/theos-action@v1.4
      with:
        # Where to install Theos
        theos-dir: ${{ github.workspace }}/theos
        # Where to clone Theos from (git URL)
        theos-src: https://github.com/theos/theos
        # Where to clone the iOS SDKs from (GitHub repository URL)
        theos-sdks: https://github.com/theos/sdks
        # Which branch to clone from SDK repo
        theos-sdks-branch: master
        # Whether to enable Orion, which adds support for Swift tweaks
        orion: false
    - name: Run build script
      run: chmod +x ./build.sh && ./build.sh
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
        -t 'Release ${{ github.ref_name }}'
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' packages/**
        --repo '${{ github.repository }}'
    
